const express = require('express');
const app = express();
const port = 3000;

const redirects = {
  "darren": "https://darrentravel.com/",
  "dominik": "https://twitter.com/dominiksumer",
  "felix": "https://twitter.com/scholz_felix",
  "itsanishjain": "https://twitter.com/itsanishjain",
  "julien": "https://twitter.com/JhumanJ",
  "kevin": "https://kevinisaac.in/",
  "matt": "https://twitter.com/Matthew_Reid",
  "nandha": "https://twitter.com/nandhaKT",
  "rogerswannell": "https://rogerswannell.com/projects/",
  "talha": "https://twitter.com/Talhaverse",
  "kin-shah": "https://therockstardba.github.io/kin-dbsre/",
  "govind": "https://taglog.me/realzenfox/buildinpublic",
  "pascal": "https://pascal.works/inpublic",
  "krish": "https://twitter.com/krishrshah",
  "daniela": "https://twitter.com/NerdDoingSocial",
  "sebastian": "https://twitter.com/SebDugudae",
  "thewebdevguy": "https://twitter.com/the_webdevguy",
  "morris": "https://twitter.com/ThatMattMorris",
  "shubhxms": "https://shubhxms.github.io/",
  "aprilynne": "https://twitter.com/AprilynneAlter",
  "yash": "https://twitter.com/yhdesai",
  "calix": "https://calix.dev/",
  "rishi": "https://twitter.com/rishibuilding",
  "josh": "https://twitter.com/joshmanders",
  "albert": "https://twitter.com/mazard",
  "james": "https://jameskenny.dev/",
  "brandon": "https://brackets.gg/",
  "propelteams": "https://propelteams.com/",
  "arjun": "https://www.uxperiments.io/",
  "jack": "https://twitter.com/jacksbridger",
  "mahfudz": "https://twitter.com/mmhfdz",
  "arvid": "https://twitter.com/arvidkahl",
  "blakey": "https://twitter.com/yekalb",
  "seyi": "https://twitter.com/wadboy_",
  "joe": "https://twitter.com/joemasilotti",
  "kory": "https://fitflows.co/",
  "raz": "https://twitter.com/razvanilin",
  "dineshs": "https://twitter.com/SDinesh91",
  "veer": "https://veerdosi.com/",
  "joel": "https://twitter.com/Joel_Rain2o",
  "kevon": "https://twitter.com/MeetKevon",
  "miguel": "https://twitter.com/mmduarte",
  "annasy": "https://twitter.com/annasycanvas",
  "tanya": "https://hayzelmedia.com/",
  "jake": "https://www.batsuuri.ca/",
  "wilbertliu": "https://twitter.com/wilbertliu",
  "rhys": "https://twitter.com/rhysbmorgan",
  "hdkstr": "https://twitter.com/search?q=%23buildinpublic%20from%3Ahdkstr&src=typed_query&f=top",
  "toli": "https://toli.notion.site/",
  "diego": "https://twitter.com/diegopixel_",
  "christine": "https://twitter.com/christinetrac1",
  "jmckinven": "https://twitter.com/jmckinven",
  "anita": "https://twitter.com/anitakirkovska",
  "ayush": "https://twitter.com/ayushtweetshere",
  "wilson": "https://euboid.com/",
  "freeze": "https://twitter.com/freezebrain",
  "mattia": "https://twitter.com/heymattia",
  "leif": "https://twitter.com/leifjerami",
  "jason": "https://twitter.com/jasonleowsg",
  "sahil": "https://twitter.com/sahilypatel",
  "helen": "https://www.helenhuang.io/",
  "sudham": "https://twitter.com/sudhamjayanthi",
  "kunal": "https://kunal.tech/",
  "lars": "https://larswiegers.nl/",
  "dennis": "https://twitter.com/denniscessan",
  "yuyu": "https://www.yuurrific.com/",
  "ashishselvaraj": "https://www.ashishselvaraj.com/",
  "ramyachinnadurai": "https://twitter.com/code_rams",
  "somil": "https://twitter.com/somil_agg",
  "mithilesh": "https://twitter.com/Mithilesh_1609",
  "micah": "https://openmakers.io/MicahIverson",
  "juan": "https://twitter.com/juanhenriqz",
  "eddie": "https://twitter.com/thinkknight",
  "callum": "https://twitter.com/callum_codes",
  "amina": "https://twitter.com/aminaighoud",
  "matthias": "https://newsbundler.com/",
  "rae": "https://raewilliams.co/",
  "rich": "https://twitter.com/rdjpalmer",
  "david": "https://twitter.com/iamdavidhill",
  "noah": "https://twitter.com/noahflk",
  "kai": "https://twitter.com/kaioelfke",
  "adi": "https://adi.so/",
  "mudrankgupta": "https://twitter.com/mudrankgupta",
  "an": "https://anthemaker.com/",
  "bruce": "https://bml.bio.link/",
  "lokesh": "https://lokeshvarman.github.io/",
  "indiestartupman": "https://twitter.com/IndieStartupman",
  "brody": "https://brodyluebkeman.com/",
  "fardeen": "https://twitter.com/fardeenxyz",
  "ilya": "https://twitter.com/ilyapas",
  "farid": "https://faridbouchdak.com/",
  "martin": "https://twitter.com/martinstellar",
  "dagobert": "https://twitter.com/dagorenouf",
  "joshua": "https://getchirrapp.com/@joshpitzalis",
  "spilth": "https://spilth.org/",
  "knight": "https://twitter.com/imknight",
  "stephen": "https://twitter.com/stevediaconou",
  "ind": "https://kodekeras.my.id/",
  "bill": "https://twitter.com/billhinostroza",
  "elsie": "https://www.getmicro.app/",
  "bagelsangranola": "https://twitter.com/bagelsangranola",
  "chariceyam": "https://twitter.com/ChariceYam",
  "djchuang": "https://djchuang.com/",
  "apvarun": "https://twitter.com/apvarun",
  "giancarlo": "https://twitter.com/gc_psk",
  "daniel": "https://dseoane.com/",
  "aditya": "https://shimy.in/",
  "piotr": "https://twitter.com/piotrkulpinski",
  "fitdollar": "https://fitdollar.com/",
  "milly": "https://birkwood.co/",
  "tad": "https://www.tadscritchfield.com/",
  "akg": "https://shimy.in/",
  "ahad": "https://www.ahadsheriff.com/",
  "dan": "https://danferg.com/",
  "kyle": "https://www.kyleshook.com/",
  "idan": "https://twitter.com/idanmasas",
  "nikhil": "Https://👽🤖🚀.y.at",
  "victor": "https://twitter.com/victor_bigfield",
  "ojs": "https://ojs-services.com/",
};

app.get('/', (req, res) => {
  const host = req.get('host');
  const subdomain = host.split('.')[0];

  const redirectTo = redirects[subdomain];
  if (redirectTo) {
      res.redirect(301, redirectTo);
  } else {
      res.status(404).send('Subdomain not found');
  }
});

app.listen(port, () => {
  console.log(`Server running on http://localhost:${port}`);
});